### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [letsar/flutter_sticky_header#57]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:flutter_sticky_header`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
Blocked by letsar/value_layout_builder#3

**Comment by IchordeDionysos** [comment]
The new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by zs-dima** [comment]
Any updates on this issue are welcome

**Comment by ThexXTURBOXx** [comment]
Workaround, use this version here:
```
  flutter_sticky_header:
    git:
      url: https://github.com/Femtopedia/flutter_sticky_header.git
      ref: master
```
